version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    env_file:
      - ./.env.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo:7.0.5-rc0
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - ./mongodb/db:/data/db
    expose:
    - 27017
    ports:
      - "26017:27017"
  
